---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a new Content Delivery Network (CDN) distribution and attaches it to an ELB.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    LoadBalancerDomainName:
        Description: 'DNS name of the load balancer to bind to the distribution'
        Type: 'String'

    LoadBalancerPort:
        Description: 'Port the load balancer is listening on'
        Type: 'Number'

    WAF:
        Description: 'The AWS WAF to associate with this distribution.'
        Type: 'String'

    Bucket:
        Description: 'DNS name of the S3 bucket to dump logs into, eg mystack-mybucket-kdwwxmddtr2g.s3.amazonaws.com'
        Type: 'String'

Resources:
    Distribution:
        Type: 'AWS::CloudFront::Distribution'
        Properties:
            DistributionConfig:
                Comment: 'I wish we could tag this resource somehow'
                DefaultCacheBehavior:
                    AllowedMethods:
                        - "DELETE"
                        - "GET"
                        - "HEAD"
                        - "OPTIONS"
                        - "PATCH"
                        - "POST"
                        - "PUT"
                    CachedMethods:
                        - "GET"
                        - "HEAD"
                        - "OPTIONS"
                    Compress: true
                    DefaultTTL: 86400
                    ForwardedValues:
                        Headers:
                            - "*"
                        QueryString: true
                    MaxTTL: 31536000
                    SmoothStreaming: false
                    TargetOriginId: 'ELB'
                    ViewerProtocolPolicy: 'redirect-to-https'
                Enabled: true
                HttpVersion: 'http2'
                Logging:
                    Bucket:
                        Ref: Bucket
                    IncludeCookies: true
                Origins:
                    - DomainName: !Ref LoadBalancerDomainName
                      Id: 'ELB'
                      CustomOriginConfig:
                            HTTPPort: !Ref LoadBalancerPort
                            OriginProtocolPolicy: 'http-only'
                PriceClass: 'PriceClass_All'
                ViewerCertificate:
                    CloudFrontDefaultCertificate: true
                WebACLId:
                    Ref: WAF

Outputs:
    Distribution:
        Description: ID of the CloudFront Distribution
        Value:
            Ref: Distribution

    DomainName:
        Description: The DNS name referencing the Distribution
        Value: !GetAtt Distribution.DomainName
